# Generated by Django 5.0.7 on 2024-07-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='summa',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='umumiy narxi'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=200, verbose_name='manzil'),
        ),
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Kompaniya nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.PositiveIntegerField(verbose_name='soni'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='qty',
            field=models.PositiveIntegerField(verbose_name='soni'),
        ),
    ]
